In [1]:
import os
os.chdir("../")

In [2]:
import os

import awswrangler as wr
from helpers.datacleaning import drop_na, assign_region, extract_state, drop_bad_addresses, generate_sales_data, get_bean_data

#def process_sales_function(event, context):
source_df = wr.s3.read_csv(
    "s3://de-sales-data-project-raw-data-146479615822/Online_Shopping_Dataset.csv"
)

    #make daily data
df = generate_sales_data(source_df)
    #cleaners
df = drop_na(df)
df = drop_bad_addresses(df)
df = extract_state(df)
df = assign_region(df)
#df = wr.catalog.sanitize_dataframe_columns_names(df)   
table_name = "sales_data"
wr.s3.to_parquet(
        df, 
        path = f"s3://de-sales-data-project-data-lake-146479615822/{table_name}/",
                dataset=True,
                table=table_name,
                database="data_lake",
                mode="overwrite_partitions",
                partition_cols=["Date"],
                )

KeyError: 'Address'

In [5]:
df.head()

,date,customer,address,bean_type,amount_purchased_lbs_,purchase_cost_,sell_price_,profit_,state,region
0,2025-04-12,Hacienda Kitchen Smokehouse,"2276 N 3rd St, Baton Rouge, LA",Borlotti Beans,3523,2994.55,8983.65,5989.10,LA,South East
1,2025-04-12,Native Foods,"808 5th Ave SE, Olympia, WA",Pink Beans,1757,790.65,2371.95,1581.30,WA,North West
2,2025-04-12,Ocotillo Agave Cantina,"2150 Hancock St, San Diego, CA",Soybeans,3837,959.25,2877.75,1918.50,CA,West
3,2025-04-12,Panda Express,"1216 Gallatin Ave, Nashville, TN",Lentils,2573,720.44,2161.32,1440.88,TN,South East
4,2025-04-12,Lentil & Greens,"1150 11th Ave, Helena, MT",Black Beans,2565,820.80,2462.40,1641.60,MT,North West

In [7]:
source_df.head()

,Date,Customer,Address,Bean Type,Amount Purchased lbs,Purchase Cost,Sell Price,Profit
0,3/1/2025,Sienna Fork Healthy Eats,"1444 43rd Ave NE, Bismarck, ND",Lentils,1577,441.56,1324.68,883.12
1,3/1/2025,El Pollo Loco,"907 W 5th St, Austin, TX",Pinto Beans,7940,2382.00,7146.00,4764.00
2,3/1/2025,Hacienda Kitchen Smokehouse,"2276 N 3rd St, Baton Rouge, LA",Pinto Beans,2925,877.50,2632.50,1755.00
3,3/1/2025,Native Foods,"808 5th Ave SE, Olympia, WA",Lentils,891,249.48,748.44,498.96
4,3/1/2025,Ocotillo Agave Cantina,"2150 Hancock St, San Diego, CA",Black Beans,3010,963.20,2889.60,1926.40